version: "2"
linters:
  default: standard
  enable:
    - govet
    - staticcheck
    - gosec
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - err113
    - gocritic